[server_http_api]
bind_addr_http = ":8088"
read_timeout = 8 #seconds
write_timeout = 8 #seconds
protocol = "http"

[context]
timeout = 8 #seconds

[logger]
log_level = "debug"
log_path = "logs/api/debug/"

[S3]
endpoint = "http://localstack:4566"

[server_grpc_image]
URL = "image:8089"
work_timeout = 3 #seconds

[cors]
methods = ["POST", "GET", "PUT"]
urls = ["http://localhost:3000", "http://movie-gate.online"]
headers = ["Content-Type", "Content-Length", "X-Csrf-Token"]
credentials = true
debug = true
