[server_http]
bind_addr_http = "0.0.0.0:8088"
read_timeout = 10 #seconds
write_timeout = 10 #seconds
protocol = "https"
tls_certificate_file = "fullchain.pem"
tls_key_file = "privkey.pem"

[context]
timeout = 10 #seconds

[logger]
log_level = "debug"
log_path = "logs/api/prod"

[S3]
endpoint = "http://localstack:4566"

[cors]
methods = ["POST", "GET", "PUT", "DELETE"]
urls = ["https://movie-gate.online", "http://localhost:8088", "https://localhost:8088"]
headers = ["Content-Type", "Content-Length", "X-Csrf-Token"]
credentials = true
debug = false
