[server_http_api]
service_name = "api"
bind_addr_http = "0.0.0.0:8088"
read_timeout = 10 #seconds
write_timeout = 10 #seconds
protocol = "https"
tls_certificate_file = "./fullchain.pem"
tls_key_file = "./privkey.pem"

[metrics]
bind_addr_http = ":9001"

[context]
timeout = 10 #seconds

[logger]
log_level = "debug"
log_path = "logs/api/prod/"

[server_grpc_image]
URL = "image:8089"
work_timeout = 3 #seconds

[server_grpc_warehouse]
URL = "warehouse:8090"
work_timeout = 3 #seconds

[server_grpc_auth]
URL = "auth:8091"
work_timeout = 3 #seconds

[cors]
methods = ["POST", "GET", "PUT", "DELETE"]
urls = ["https://movie-gate.ru", "http://localhost:8088", "https://localhost:8088", "http://localhost:3000", "https://localhost:3000"]
headers = ["Content-Type", "Content-Length", "X-Csrf-Token"]
credentials = true
debug = false
