version: "3.7"

services:
  main:
    container_name: "main"
    networks:
      - localstack-net
      - postgres-net
    image: andeo1812/golang_web:latest
    command: make -C project debug-mode
    environment:
      AWS_PROFILE: "${AWS_PROFILE}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
    volumes:
      - .:/project
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8088:8088"
    depends_on:
      - localstack
      - main_db


  localstack:
    hostname: localstack
    networks:
      - localstack-net
    container_name: "localstack"
    image: localstack/localstack:latest
    restart: unless-stopped
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - EXTERNAL_HOSTNAME=localstack

      - SERVICES=s3
      # - DEBUG=1

      - DATA_DIR=/tmp/localstack/data
      - EAGER_SERVICE_LOADING=1
      - LEGACY_DIRECTORIES=1

      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_REMOVE_CONTAINERS=true

      - KINESIS_STREAM_SHARDS=1
      - KINESIS_ERROR_PROBABILITY=0.0
      - KINESIS_STREAM_NAME=kinesis-stream
      - KINESIS_PROVIDER=kinesalite

      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
    ports:
      - "4566-4599:4566-4599"


  main_db:
    container_name: "main_db"
    networks:
      - postgres-net
    image: postgres:latest
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"


  admin_db:
    container_name: "admin_db"
    networks:
      - postgres-net
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - main_db

  monitor_db:
    container_name: "monitor_db"
    networks:
      - postgres-net
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_URI: "main_db:5432/${POSTGRES_DB}?sslmode=disable"
      DATA_SOURCE_USER: "${POSTGRES_USER}"
      DATA_SOURCE_PASS: "${POSTGRES_PASSWORD}"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./scripts/queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187:9187"
    depends_on:
      - main_db


networks:
  localstack-net:
    external: false
    driver: bridge
    name: localstack-net
  postgres-net:
    driver: bridge
    name:   postgres-net
