version: "3.7"

services:
  app:
    container_name: "app"
    networks:
      - localstack-net
      - postgres-net
    image: andeo1812/golang_web:latest
    command: make -C project debug-mode
    environment:
      - AWS_PROFILE=default
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_REGION=us-east-1
    volumes:
      - .:/project
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8088:8088"


  localstack:
    hostname: localstack
    networks:
      - localstack-net
    container_name: "localstack"
    image: localstack/localstack:latest
    restart: unless-stopped
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - EXTERNAL_HOSTNAME=localstack

      - SERVICES=s3
      # - DEBUG=1

      - DATA_DIR=/tmp/localstack/data
      - EAGER_SERVICE_LOADING=1
      - LEGACY_DIRECTORIES=1

      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_REMOVE_CONTAINERS=true

      - KINESIS_STREAM_SHARDS=1
      - KINESIS_ERROR_PROBABILITY=0.0
      - KINESIS_STREAM_NAME=kinesis-stream
      - KINESIS_PROVIDER=kinesalite

      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
    ports:
      - "4566-4599:4566-4599"


  db:
    container_name: "db"
    networks:
      - postgres-net
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - .:/var/lib/postgresql/data
      - ./bin:/docker-entrypoint-initdb.d


#  dbadmin:
#    container_name: "dbadmin"
#    networks:
#      - postgres
#    image: dpage/pgadmin4:5.7
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
#      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4habr"
#      PGADMIN_CONFIG_SERVER_MODE: "False"
#    volumes:
#      - ./pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    restart: unless-stopped
#
#  dbmonitor:
#    container_name: dbmonitor
#    networks:
#      - postgres-net
#    image: prometheuscommunity/postgres-exporter:v0.10.0
#    environment:
#      DATA_SOURCE_URI: "postgres:5432/habrdb?sslmode=disable"
#      DATA_SOURCE_USER: "habrpguser"
#      DATA_SOURCE_PASS: "pgpwd4habr"
#      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
#    volumes:
#      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
#    ports:
#      - "9187:9187"
#    restart: unless-stopped

networks:
  localstack-net:
    external: false
    driver: bridge
    name: localstack-net
  postgres-net:
    external: false
    driver: bridge
    name:   postgres-net
