version: "3.7"

services:
  dev:
    container_name: "dev"
    networks:
      - localstack-net
      - postgres-net
    image: lonkidely/golang_web_light:latest
    environment:
      AWS_PROFILE: "${AWS_PROFILE}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_SSLMODE: "${POSTGRES_SSLMODE}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    volumes:
      - .:/project
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"


  api:
    container_name: "api"
    networks:
      - postgres-net
    build: ./
    command: sh -c "cd app && ./api_bin -config-path=./configs/prod.toml"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_SSLMODE: "${POSTGRES_SSLMODE}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    volumes:
      - ./logs/api/prod:/logs/api/prod
      - ./cmd/api:/app
    ports:
      - "8088:8088"
    depends_on:
      - image
      - warehouse
    restart: unless-stopped

  image:
    container_name: "image"
    networks:
      - localstack-net
      - postgres-net
    build: ./
    command: sh -c "./app/image_bin -config-path=./app/configs/prod.toml"
    environment:
      AWS_PROFILE: "${AWS_PROFILE}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "${AWS_REGION}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_SSLMODE: "${POSTGRES_SSLMODE}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    volumes:
      - ./logs/image:/logs/image
      - ./cmd/image:/app
    ports:
      - "8089:8089"
    depends_on:
      - localstack
      - main_db


  warehouse:
    container_name: "warehouse"
    networks:
      - postgres-net
    build: ./
    command: sh -c "./app/warehouse_bin -config-path=./app/configs/prod.toml"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_SSLMODE: "${POSTGRES_SSLMODE}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    volumes:
      - ./logs/warehouse:/logs/warehouse
      - ./cmd/warehouse:/app
    ports:
      - "8090:8090"
    depends_on:
      - main_db

  auth:
    container_name: "auth"
    networks:
      - postgres-net
    build: ./
    command: sh -c "./app/auth_bin -config-path=./app/configs/prod.toml"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_SSLMODE: "${POSTGRES_SSLMODE}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    volumes:
      - ./logs/auth:/logs/auth
      - ./cmd/auth:/app
    ports:
      - "8091:8091"
    depends_on:
      - main_db


  localstack:
    hostname: localstack
    networks:
      - localstack-net
    container_name: "localstack"
    image: localstack/localstack:latest
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}

      - LOCALSTACK_HOSTNAME=localstack
      - EXTERNAL_HOSTNAME=localstack

      - SERVICES=s3
      # - DEBUG=1

      - DATA_DIR=/tmp/localstack/data
      - EAGER_SERVICE_LOADING=1
      - LEGACY_DIRECTORIES=1

      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_REMOVE_CONTAINERS=true

      - KINESIS_STREAM_SHARDS=1
      - KINESIS_ERROR_PROBABILITY=0.0
      - KINESIS_STREAM_NAME=kinesis-stream
      - KINESIS_PROVIDER=kinesalite

      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./data:/tmp/localstack
      # - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d
    ports:
      - "4566-4599:4566-4599"


  main_db:
    container_name: "main_db"
    networks:
      - postgres-net
    image: postgres:latest
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=512MB"
      - "-c"
      - "effective_cache_size=512MB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=1GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - "pg_stat_statements.track_utility=false"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    restart: unless-stopped


  admin_db:
    container_name: "admin_db"
    networks:
      - postgres-net
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:5050"
    restart: unless-stopped
    depends_on:
      - main_db


  monitor_db:
    container_name: "monitor_db"
    networks:
      - postgres-net
    image: prometheuscommunity/postgres-exporter:latest
    environment:
      DATA_SOURCE_URI: "main_db:5432/${POSTGRES_DB}?sslmode=disable"
      DATA_SOURCE_USER: "${POSTGRES_USER}"
      DATA_SOURCE_PASS: "${POSTGRES_PASSWORD}"
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./scripts/queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - "9187:9187"
    depends_on:
      - main_db
    restart: unless-stopped


networks:
  localstack-net:
    external: false
    driver: bridge
    name: localstack-net
  postgres-net:
    driver: bridge
    name: postgres-net
