[server_http]
bind_addr_http = ":8088"
read_timeout = 10
write_timeout = 10
protocol = "http"

[context]
timeout = 10

[logger]
log_level = "debug"
log_path = "logs/debug/"

[S3]
endpoint = "http://localstack:4566"

[URLs]
image_service = "image:8089"

[cors]
methods = ["POST", "GET", "PUT"]
urls = ["http://localhost:3000", "http://movie-gate.online"]
headers = ["Content-Type", "Content-Length", "X-Csrf-Token"]
credentials = true
debug = true
