[server]
bind_addr_http = ":8088"
read_timeout = 10
write_timeout = 10

[context]
timeout = 10

[logger]
log_level = "debug"
log_path = "localhost"

[S3]
region = "us-east-1"
endpoint = "http://localhost:4566"
aws_access_key_id = "foo"
aws_secret_access_key = "bar"

[cors]
methods = ["POST", "GET"]
urls = ["http://localhost:3001"]
headers = ["Content-Type", "Content-length"]
credentials = true
debug = true
