[server]
bind_addr_http = ":8088"
read_timeout = 10
write_timeout = 10

[context]
timeout = 10

[logger]
log_level = "debug"
log_path = "localhost"

[S3]
endpoint = "http://localstack:4566"

[cors]
methods = ["POST", "GET", "OPTIONS"]
urls = ["http://localhost:3000", "http://movie-gate.online"]
headers = ["Content-Type", "Content-Length"]
credentials = true
debug = true

URL = "postgresql://mguser:mgpass@localhost:5432/mgdb?sslmode=disable"
