{
 "title": "main",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "microservice api",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "api_total_hits{job=\"api\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "api_success_hits{job=\"api\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "api_errors_hits{job=\"api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "api execution sum",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 8, "y": 0 },
   "targets": [
    { "expr": "api_durations_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "image microservice",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 15 },
   "targets": [
    { "expr": "image_total_hits", "legendFormat": "__auto" },
    { "expr": "image_success_hits", "legendFormat": "__auto" },
    { "expr": "image_errors_hits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "image execution sum",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 8, "y": 15 },
   "targets": [
    { "expr": "image_durations_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "auth mircoservice",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 30 },
   "targets": [
    { "expr": "auth_total_hits", "legendFormat": "__auto" },
    { "expr": "auth_success_hits", "legendFormat": "__auto" },
    { "expr": "auth_errors_hits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "auth execution sum",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 8, "y": 30 },
   "targets": [
    { "expr": "auth_durations_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "mircoservice warehouse",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 45 },
   "targets": [
    { "expr": "warehouse_total_hits", "legendFormat": "__auto" },
    { "expr": "warehouse_success_hits", "legendFormat": "__auto" },
    { "expr": "warehouse_errors_hits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "warehouse execution sum",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 8, "y": 45 },
   "targets": [
    { "expr": "warehouse_durations_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "node_exporter",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 60 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "main_db",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 8, "y": 60 },
   "targets": [
    { "expr": "pg_stat_database_active_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active RAM",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    { "expr": "node_memory_Active_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU seconds",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 8, "y": 75 },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}