// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( UserSignupRequest ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* UserSignupRequest ) UnmarshalJSON([]byte) error { return nil }
func ( UserSignupRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UserSignupRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UserSignupRequest *UserSignupRequest

func ( UserSignupResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* UserSignupResponse ) UnmarshalJSON([]byte) error { return nil }
func ( UserSignupResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* UserSignupResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_UserSignupResponse *UserSignupResponse
