// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package security

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5205c11aDecodeGoParkMailRu20222BugOverloadInternalPkgSecurity(in *jlexer.Lexer, out *TokenData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "SessionID":
			out.SessionID = string(in.String())
		case "User":
			(out.User).UnmarshalEasyJSON(in)
		case "Exp":
			out.Exp = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5205c11aEncodeGoParkMailRu20222BugOverloadInternalPkgSecurity(out *jwriter.Writer, in TokenData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"SessionID\":"
		out.RawString(prefix[1:])
		out.String(string(in.SessionID))
	}
	{
		const prefix string = ",\"User\":"
		out.RawString(prefix)
		(in.User).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"Exp\":"
		out.RawString(prefix)
		out.Int64(int64(in.Exp))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TokenData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5205c11aEncodeGoParkMailRu20222BugOverloadInternalPkgSecurity(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TokenData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5205c11aEncodeGoParkMailRu20222BugOverloadInternalPkgSecurity(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TokenData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5205c11aDecodeGoParkMailRu20222BugOverloadInternalPkgSecurity(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TokenData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5205c11aDecodeGoParkMailRu20222BugOverloadInternalPkgSecurity(l, v)
}
