INSERT INTO genres (name)
VALUES ('аниме'),
       ('биография'),
       ('боевик'),
       ('вестерн'),
       ('военный'),
       ('детектив'),
       ('детский'),
       ('документальный'),
       ('драма'),
       ('игра'),
       ('история'),
       ('комедия'),
       ('концерт'),
       ('короткометражка'),
       ('криминал'),
       ('мелодрама'),
       ('музыка'),
       ('мультфильм'),
       ('мюзикл'),
       ('приключения'),
       ('семейный'),
       ('спорт'),
       ('ток-шоу'),
       ('триллер'),
       ('ужасы'),
       ('фантастика'),
       ('фильм-нуар'),
       ('фэнтези'),
       ('церемония'),
       ('новости'),
       ('сериал'),
       ('реальное ТВ');

INSERT INTO countries (name)
VALUES ('Австралия'),
       ('Австрия'),
       ('Аргентина'),
       ('Бангладеш'),
       ('Беларусь'),
       ('Бельгия'),
       ('Великобритания'),
       ('Греция'),
       ('Грузия'),
       ('Дания'),
       ('Египет'),
       ('Израиль'),
       ('Индия'),
       ('Испания'),
       ('Италия'),
       ('Казахстан'),
       ('Канада'),
       ('Катар'),
       ('Китай'),
       ('Латвия'),
       ('Литва'),
       ('Новая Зеландия'),
       ('Норвегия'),
       ('ОАЭ'),
       ('Польша'),
       ('Португалия'),
       ('Россия'),
       ('США'),
       ('СССР'),
       ('Словакия'),
       ('Словения'),
       ('Финляндия'),
       ('Франция'),
       ('Чехия'),
       ('Чехословакия'),
       ('Швейцария'),
       ('Швеция'),
       ('Япония'),
       ('Мексика'),
       ('Тайвань'),
       ('Тунис'),
       ('Германия'),
       ('Венгрия');

INSERT INTO professions (name)
VALUES ('актер'),
       ('режиссер'),
       ('сценарист'),
       ('продюсер'),
       ('оператор'),
       ('композитор'),
       ('художник'),
       ('монтажер');

INSERT INTO tags (name, description)
VALUES ('популярное', 'Самые популярные фильмы в сообществе'),
       ('сейчас в кино', 'Фильмы, которые можно посомотреть в российском кинопрокате');

INSERT INTO companies (name)
VALUES ('20th Century Fox'),
       ('20th Century Fox Animation'),
       ('A24'),
       ('Amazon Prime Video'),
       ('Alcon Entertainment'),
       ('Amblin Entertainment'),
       ('Bad Robot Productions'),
       ('BBC Films'),
       ('BBC Television Centre'),
       ('Blue Sky Studios'),
       ('Blumhouse Productions'),
       ('Canal+'),
       ('Carolco Pictures'),
       ('Castle Rock Entertainment'),
       ('Columbia Pictures'),
       ('DC Comics'),
       ('Decca Records'),
       ('DreamWorks Animation'),
       ('DreamWorks Pictures'),
       ('EuropaCorp'),
       ('Focus Features'),
       ('Gaumont'),
       ('HBO'),
       ('Illumination Entertainment'),
       ('Lakeshore Entertainment'),
       ('Legendary Pictures'),
       ('Lionsgate'),
       ('Lucasfilm'),
       ('Marvel Studios'),
       ('Metro-Goldwyn-Mayer'),
       ('Millennium Films'),
       ('Miramax Films'),
       ('Netflix'),
       ('New Line Cinema'),
       ('Nickelodeon Movies'),
       ('Original Film'),
       ('Paramount Pictures'),
       ('Pathé'),
       ('Pixar Animation Studios'),
       ('Polydor Records'),
       ('Regency Enterprises'),
       ('Relativity Media'),
       ('Screen Gems'),
       ('Skydance Media'),
       ('Sony BMG Music Entertainment'),
       ('Sony Pictures Animation'),
       ('Sony Pictures Entertainment'),
       ('Studio Canal'),
       ('Studio Ghibli'),
       ('Summit Entertainment'),
       ('The Weinstein Company'),
       ('Touchstone Pictures'),
       ('TriStar Pictures'),
       ('United Artists'),
       ('Universal Music Records'),
       ('Universal Pictures'),
       ('Village Roadshow Pictures'),
       ('Walt Disney Animation Studios'),
       ('Walt Disney Pictures'),
       ('Warner Bros. Pictures'),
       ('Ленфильм'),
       ('Мосфильм'),
       ('Союзмультфильм'),
       ('Централ Партнершип'),
       ('Infinity Films'),
       ('Natrix Natrix'),
       ('Eurimages');
