route:
  receiver: gmail

receivers:
  - name: gmail
    email_configs:
      - to: alexanforall@gmail.com
        from: doping777123@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: doping777123@gmail.com
        auth_identity: doping777123@gmail.com
        auth_password: etwcwvloiuygotvk
