[server]
bind_addr_http = ":8088"
read_timeout = 4
write_timeout = 4

[context]
timeout = 4

[logger]
log_level = "info"
log_path = "movie-gate"

[S3]
endpoint = "http://localstack:4566"

[cors]
methods = ["POST", "GET", "PUT"]
urls = ["http://movie-gate.online", "https://movie-gate.online", "https://www.movie-gate.online", "https://movie-gate.online:443"]
headers = ["Content-Type", "Content-Length", "X-Csrf-Token"]
credentials = true
debug = false
