[server]
bind_addr_http = ":8088"
read_timeout = 4
write_timeout = 4

[context]
timeout = 4

[logger]
log_level = "info"
log_path = "movie-gate"

[S3]
endpoint = "http://localstack:4566"
region = "us-east-1"

[cors]
methods = ["POST", "GET"]
urls = ["http://movie-gate.online/"]
headers = ["Content-Type", "Content-length"]
credentials = true
debug = false
