[database]
URL = "user=mguser dbname=mgdb password=mgpass host=localhost port=5432 sslmode=disable"
#seconds
timeout = 1

[volume]
count_users = 5
count_views = 40
count_ratings = 120
count_collections = 30
count_reviews = 30
max_length_review_body = 150
count_reviews_likes = 200
