[database]
URL = "user=mguser dbname=mgdb password=mgpass host=localhost port=5432 sslmode=disable"
#seconds
timeout = 1

[volume]
count_users = 10
count_views = 40
count_ratings = 120
count_collections = 30
count_reviews = 30
max_length_review_body = 150
max_likes_on_review = 6
max_reviews_on_film = 8
count_reviews_likes = 25
