[database]
URL = "user=mguser dbname=mgdb password=mgpass host=localhost port=5432 sslmode=disable"

[volume]
count_users = 5
count_profile_views = 5
count_profile_ratings = 5
count_profile_collections = 5
count_reviews = 5
count_reviews_likes = 5
