[database]
timeout = 1

[volume]
count_users = 200

count_ratings = 600
max_rating = 10
max_count_ratings_on_film = 20

count_reviews = 0
max_length_review_body = 0
max_reviews_on_film = 0
count_reviews_likes = 0
max_likes_on_review = 0

max_film_actors = 5
max_film_persons = 4
max_films_in_tag = 20

count_views = 600
max_views_on_film = 15

count_collections = 30
