[database]
timeout = 1

[volume]
count_users = 200

count_ratings = 600
max_rating = 10
max_count_ratings_on_film = 20

count_reviews = 600
max_length_review_body = 150
max_reviews_on_film = 50
count_reviews_likes = 3000
max_likes_on_review = 20

max_film_actors = 5
max_film_persons = 2
max_films_in_tag = 20

count_views = 600
max_views_on_film = 15

count_collections = 30
