[server_grpc_image]
service_name = "image"
bind_addr_http = ":8089"
connection_timeout = 10 #seconds

[metrics]
bind_addr_http = ":9002"

[logger]
log_level = "debug"
log_path = "logs/image/debug/"

[S3]
endpoint = "http://localstack:4566"

[database_params]
max_open_cons = 20
