on: push

jobs:
  check:
    runs-on: ubuntu-latest
    container: andeo1812/golang_web
    steps:
      - uses: actions/checkout@v2
      - run: make check
  build:
    runs-on: ubuntu-latest
    container: andeo1812/golang_web
    needs: [ check ]
    steps:
      - uses: actions/checkout@v2
      - run: make build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: main
  tests:
    runs-on: ubuntu-latest
    container: andeo1812/golang_web
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - run: make run-tests
#    env:
#      AWS_PROFILE: ${{ secrets.AWS_PROFILE }}
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      AWS_REGION: ${{ secrets.AWS_REGION }}
#      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
#      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
#      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
#      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
#      POSTGRES_SSLMODE: ${{ secrets.POSTGRES_SSLMODE }}
#      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
